/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Hospital } from "./Hospital";
export type { Patient } from "./Patient";
export type { Ownable } from "./Ownable";

export { Hospital__factory } from "./factories/Hospital__factory";
export { Patient__factory } from "./factories/Patient__factory";
export { Ownable__factory } from "./factories/Ownable__factory";
